# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0003_auto_20171201_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='slip',
            field=models.ImageField(default='../static/imgs/empty.png', max_length=500,
                                    upload_to="imgs/<class 'datetime.date'>/"),
        ),
    ]
