# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171005_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pic',
            field=models.ImageField(default='../static/imgs/empty.png', upload_to='imgs/'),
        ),
    ]
