# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 05:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20171006_1231'),
        ('main', '0004_auto_20171005_2013'),
    ]

    operations = [
    ]
